AcunMedyaAkademiPortfolio/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaAkademiPortfolio.Controllers
{
    public class AdminLayoutController : Controller
    {
        // GET: AdminLayout
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult _HeaderPartial()
        {
            return PartialView();
        }
        public PartialViewResult _SidebarPartial()
        {
            return PartialView();
        }
        public PartialViewResult _ScriptsPartial()
        {
            return PartialView();
        }
    }
}

AcunMedyaAkademiPortfolio/Views/AdminLayout/Index.cshtml
@{
	Layout = null;
}

<!doctype html>
<html lang="en">
@Html.Action("_HeaderPartial", "AdminLayout")
<body>

	<div class="wrapper d-flex align-items-stretch">

		@Html.Action("_SidebarPartial", "AdminLayout")
		<!-- Page Content  -->
		<div id="content" class="p-4 p-md-5 pt-5">
			@RenderBody()
		</div>
	</div>

	@Html.Action("_ScriptsPartial", "AdminLayout")
</body>
</html>

AcunMedyaAkademiPortfolio/Views/AdminLayout/_HeaderPartial.cshtml
<head>
	<title>Acun Medya Portfolyo</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/Templates/sidebar-09/css/style.css">
</head>

AcunMedyaAkademiPortfolio/Views/AdminLayout/_ScriptsPartial.cshtml
<script src="/Templates/sidebar-09/js/jquery.min.js"></script>
<script src="/Templates/sidebar-09/js/popper.js"></script>
<script src="/Templates/sidebar-09/js/bootstrap.min.js"></script>
<script src="/Templates/sidebar-09/js/main.js"></script>

AcunMedyaAkademiPortfolio/Views/AdminLayout/_SidebarPartial.cshtml
<nav id="sidebar">
	<div class="custom-menu">
		<button type="button" id="sidebarCollapse" class="btn btn-primary">
		</button>
	</div>
	<div class="img bg-wrap text-center py-4" style="background-image: url(/Templates/sidebar-09/images/bg_1.jpg);">
		<div class="user-logo">
			<div class="img" style="background-image: url('/Templates/Me/icon1.jpg');"></div>
			<h3>Hasan Özbey</h3>
		</div>
	</div>
	<ul class="list-unstyled components mb-5">
		<li class="active">
			<a href="#"><span class="fa fa-home mr-3"></span> Dashboard</a>
		</li>
		<li>
			<a href="~/Templates/Me/Hasan ÖZBEY.pdf" download="Hasan ÖZBEY CV.pdf"><span class="fa fa-download mr-3 notif"><small class="d-flex align-items-center justify-content-center">5</small></span> Cv mi indir</a>
		</li>
		<li>
			<a href="/Category/CategoryList"><span class="fa fa-gift mr-3"></span> Kategoriler</a>
		</li>
		<li>
			<a href="/Project/ProjectList"><span class="fa fa-trophy mr-3"></span> Projelerim</a>
		</li>
		<li>
			<a href="/Testimonial/TestimonialList"><span class="fa fa-cog mr-3"></span> Referanslarım</a>
		</li>
		<li>
			<a href="/About/AboutList"><span class="fa fa-support mr-3"></span> Hakkımızda</a>
		</li>
		<li>
			<a href="/Service/ServiceList"><span class="fa fa-sign-out mr-3"></span> Hizmetlerim</a>
		</li>
		<li>
			<a href="/Feature/FeatureList"><span class="fa fa-sign-out mr-3"></span> Öne Çıkanlar</a>
		</li>
		<li>
			<a href="/Contact/ContactList"><span class="fa fa-sign-out mr-3"></span> Mesajlarım</a>
		</li>
		<li>
			<a href="#"><span class="fa fa-sign-out mr-3"></span> Çıkış</a>
		</li>
	</ul>

</nav>